##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    - cppcheck
    - clang-tools
    - adwaita-icon-theme
    - at-spi2-core
    - dbus
    - debhelper-compat
    - dh-sequence-gir
    - fonts-cantarell
    - fonts-dejavu-core
    - gnome-pkg-tools
    - gobject-introspection
    - gsettings-desktop-schemas
    - gtk-doc-tools
    - libatk-bridge2.0-dev
    - libatk1.0-dev
    - libcairo2-dev
    - libcolord-dev
    - libcups2-dev
    - libegl1-mesa-dev
    - libepoxy-dev
    - libfontconfig1-dev
    - libfribidi-dev
    - libgdk-pixbuf-2.0-dev
    - libgirepository1.0-dev
#    - libglib2.0-dev
    - libharfbuzz-dev
    - libjson-glib-dev
    - libpango1.0-dev
    - librest-dev
    - librsvg2-common
    - libwayland-dev
    - libx11-dev
    - libxcomposite-dev
    - libxcursor-dev
    - libxdamage-dev
    - libxext-dev
    - libxfixes-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxkbfile-dev
    - libxml2-utils
    - libxrandr-dev
    - pkg-config
    - sassc
    - wayland-protocols
    - xauth
    - xvfb

build_scripts:
#  - git clone https://github.com/cafe-desktop/clib
#  - cd clib
#  - meson . _build
#  - ninja -C _build
#  - ninja -C _build install
#  - cd ..
  - apt-get purge libglib2.0-dev -y
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure --disable-dependency-tracking --enable-broadway-backend --enable-x11-backend --enable-gtk-doc --enable-man --enable-shared --enable-introspection --enable-cloudprint --disable-static --enable-installed-tests
  - make
  - make check

after_scripts:
#  - make check

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: grapa-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.cafe-desktop.org/release
