##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:

before_scripts:
  - ./debrepo-install

build_scripts:
  - ./build-debs https://github.com/cafe-desktop/debian-packages devel ctk+3.0

after_scripts:
  - if [ -f "gen-index" ]; then ./gen-index -l 20 -i https://github.com/cafe-desktop/ctk/raw/master/demos/ctk-demo/data/16x16/ctk3-demo.png; fi
