.TH TESTGTK 1
.SH NAME
testctk \- test if the Ctk library is working
.SH SYNOPSIS
.B testctk
.SH "DESCRIPTION"
testctk is a sample program using the Ctk library. It tests all the
widgets and buttons and other fun things that Ctk lets you do,
and is a good example program to see how to make Ctk work.
.SH BUGS
Absolutely none whatsoever.
.SH AUTHOR
Peter Mattis <petm@xcf.berkeley.edu>, 
Spencer Kimball <spencer@xcf.berkeley.edu>,
and Josh MacDonald <jmacd@xcf.berkeley.edu>
