/* CTK - The GIMP Toolkit
 * Copyright (C) 1995-1997 Peter Mattis, Spencer Kimball and Josh MacDonald
 * CtkStatusbar Copyright (C) 1998 Shawn T. Amundson
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Modified by the CTK+ Team and others 1997-2000.  See the AUTHORS
 * file for a list of people on the CTK+ Team.  See the ChangeLog
 * files for a list of changes.  These files are distributed with
 * CTK+ at ftp://ftp.ctk.org/pub/ctk/.
 */

#include "config.h"

#include "ctkstatusbar.h"

#include "ctkframe.h"
#include "ctklabel.h"
#include "ctkmarshalers.h"
#include "ctkwindow.h"
#include "ctkprivate.h"
#include "ctkintl.h"
#include "ctkorientable.h"
#include "ctktypebuiltins.h"
#include "a11y/ctkstatusbaraccessible.h"

/**
 * SECTION:ctkstatusbar
 * @title: CtkStatusbar
 * @short_description: Report messages of minor importance to the user
 *
 * A #CtkStatusbar is usually placed along the bottom of an application's
 * main #CtkWindow. It may provide a regular commentary of the application's
 * status (as is usually the case in a web browser, for example), or may be
 * used to simply output a message when the status changes, (when an upload
 * is complete in an FTP client, for example).
 *
 * Status bars in CTK+ maintain a stack of messages. The message at
 * the top of the each bar’s stack is the one that will currently be displayed.
 *
 * Any messages added to a statusbar’s stack must specify a
 * context id that is used to uniquely identify
 * the source of a message. This context id can be generated by
 * ctk_statusbar_get_context_id(), given a message and the statusbar that
 * it will be added to. Note that messages are stored in a stack, and when
 * choosing which message to display, the stack structure is adhered to,
 * regardless of the context identifier of a message.
 *
 * One could say that a statusbar maintains one stack of messages for
 * display purposes, but allows multiple message producers to maintain
 * sub-stacks of the messages they produced (via context ids).
 *
 * Status bars are created using ctk_statusbar_new().
 *
 * Messages are added to the bar’s stack with ctk_statusbar_push().
 *
 * The message at the top of the stack can be removed using
 * ctk_statusbar_pop(). A message can be removed from anywhere in the
 * stack if its message id was recorded at the time it was added. This
 * is done using ctk_statusbar_remove().
 *
 * # CSS node
 *
 * CtkStatusbar has a single CSS node with name statusbar.
 */

typedef struct _CtkStatusbarMsg CtkStatusbarMsg;

struct _CtkStatusbarPrivate
{
  CtkWidget     *frame;
  CtkWidget     *label;
  CtkWidget     *message_area;

  GSList        *messages;
  GSList        *keys;

  guint          seq_context_id;
  guint          seq_message_id;
};


struct _CtkStatusbarMsg
{
  gchar *text;
  guint context_id;
  guint message_id;
};

enum
{
  SIGNAL_TEXT_PUSHED,
  SIGNAL_TEXT_POPPED,
  SIGNAL_LAST
};

static void     ctk_statusbar_update            (CtkStatusbar      *statusbar,
						 guint              context_id,
						 const gchar       *text);
static void     ctk_statusbar_destroy           (CtkWidget         *widget);

static guint              statusbar_signals[SIGNAL_LAST] = { 0 };

G_DEFINE_TYPE_WITH_PRIVATE (CtkStatusbar, ctk_statusbar, CTK_TYPE_BOX)

static void
ctk_statusbar_class_init (CtkStatusbarClass *class)
{
  CtkWidgetClass *widget_class = CTK_WIDGET_CLASS (class);

  widget_class->destroy = ctk_statusbar_destroy;

  class->text_pushed = ctk_statusbar_update;
  class->text_popped = ctk_statusbar_update;

  /**
   * CtkStatusbar::text-pushed:
   * @statusbar: the object which received the signal
   * @context_id: the context id of the relevant message/statusbar
   * @text: the message that was pushed
   *
   * Is emitted whenever a new message gets pushed onto a statusbar's stack.
   */
  statusbar_signals[SIGNAL_TEXT_PUSHED] =
    g_signal_new (I_("text-pushed"),
		  G_OBJECT_CLASS_TYPE (class),
		  G_SIGNAL_RUN_LAST,
		  G_STRUCT_OFFSET (CtkStatusbarClass, text_pushed),
		  NULL, NULL,
		  _ctk_marshal_VOID__UINT_STRING,
		  G_TYPE_NONE, 2,
		  G_TYPE_UINT,
		  G_TYPE_STRING);

  /**
   * CtkStatusbar::text-popped:
   * @statusbar: the object which received the signal
   * @context_id: the context id of the relevant message/statusbar
   * @text: the message that was just popped
   *
   * Is emitted whenever a new message is popped off a statusbar's stack.
   */
  statusbar_signals[SIGNAL_TEXT_POPPED] =
    g_signal_new (I_("text-popped"),
		  G_OBJECT_CLASS_TYPE (class),
		  G_SIGNAL_RUN_LAST,
		  G_STRUCT_OFFSET (CtkStatusbarClass, text_popped),
		  NULL, NULL,
		  _ctk_marshal_VOID__UINT_STRING,
		  G_TYPE_NONE, 2,
		  G_TYPE_UINT,
		  G_TYPE_STRING);

  /**
   * CtkStatusbar:shadow-type:
   *
   * The style of the bevel around the statusbar text.
   *
   * Deprecated: 3.20: Use CSS properties to determine the appearance,
   *    the value of this style property is ignored.
   */
  ctk_widget_class_install_style_property (widget_class,
                                           g_param_spec_enum ("shadow-type",
                                                              P_("Shadow type"),
                                                              P_("Style of bevel around the statusbar text"),
                                                              CTK_TYPE_SHADOW_TYPE,
                                                              CTK_SHADOW_IN,
                                                              CTK_PARAM_READABLE|G_PARAM_DEPRECATED));

  /* Bind class to template
   */
  ctk_widget_class_set_template_from_resource (widget_class, "/org/ctk/libctk/ui/ctkstatusbar.ui");
  ctk_widget_class_bind_template_child_internal_private (widget_class, CtkStatusbar, message_area);
  ctk_widget_class_bind_template_child_private (widget_class, CtkStatusbar, frame);
  ctk_widget_class_bind_template_child_private (widget_class, CtkStatusbar, label);

  ctk_widget_class_set_accessible_type (widget_class, CTK_TYPE_STATUSBAR_ACCESSIBLE);
  ctk_widget_class_set_css_name (widget_class, "statusbar");
}

static void
ctk_statusbar_init (CtkStatusbar *statusbar)
{
  CtkStatusbarPrivate *priv;

  statusbar->priv = ctk_statusbar_get_instance_private (statusbar);
  priv = statusbar->priv;

  priv->seq_context_id = 1;
  priv->seq_message_id = 1;
  priv->messages = NULL;
  priv->keys = NULL;

  ctk_widget_init_template (CTK_WIDGET (statusbar));
}

/**
 * ctk_statusbar_new:
 *
 * Creates a new #CtkStatusbar ready for messages.
 *
 * Returns: the new #CtkStatusbar
 */
CtkWidget* 
ctk_statusbar_new (void)
{
  return g_object_new (CTK_TYPE_STATUSBAR, NULL);
}

static void
ctk_statusbar_update (CtkStatusbar *statusbar,
		      guint	    context_id G_GNUC_UNUSED,
		      const gchar  *text)
{
  CtkStatusbarPrivate *priv;

  g_return_if_fail (CTK_IS_STATUSBAR (statusbar));

  priv = statusbar->priv;

  if (!text)
    text = "";

  ctk_label_set_text (CTK_LABEL (priv->label), text);
}

/**
 * ctk_statusbar_get_context_id:
 * @statusbar: a #CtkStatusbar
 * @context_description: textual description of what context 
 *                       the new message is being used in
 *
 * Returns a new context identifier, given a description 
 * of the actual context. Note that the description is 
 * not shown in the UI.
 *
 * Returns: an integer id
 */
guint
ctk_statusbar_get_context_id (CtkStatusbar *statusbar,
			      const gchar  *context_description)
{
  CtkStatusbarPrivate *priv;
  gchar *string;
  guint id;
  
  g_return_val_if_fail (CTK_IS_STATUSBAR (statusbar), 0);
  g_return_val_if_fail (context_description != NULL, 0);

  priv = statusbar->priv;

  /* we need to preserve namespaces on object datas */
  string = g_strconcat ("ctk-status-bar-context:", context_description, NULL);

  id = GPOINTER_TO_UINT (g_object_get_data (G_OBJECT (statusbar), string));
  if (id == 0)
    {
      id = priv->seq_context_id++;
      g_object_set_data_full (G_OBJECT (statusbar), string, GUINT_TO_POINTER (id), NULL);
      priv->keys = g_slist_prepend (priv->keys, string);
    }
  else
    g_free (string);

  return id;
}

static CtkStatusbarMsg *
ctk_statusbar_msg_create (CtkStatusbar *statusbar,
		          guint         context_id,
		          const gchar  *text)
{
  CtkStatusbarMsg *msg;

  msg = g_slice_new (CtkStatusbarMsg);
  msg->text = g_strdup (text);
  msg->context_id = context_id;
  msg->message_id = statusbar->priv->seq_message_id++;

  return msg;
}

static void
ctk_statusbar_msg_free (CtkStatusbarMsg *msg)
{
  g_free (msg->text);
  g_slice_free (CtkStatusbarMsg, msg);
}

/**
 * ctk_statusbar_push:
 * @statusbar: a #CtkStatusbar
 * @context_id: the message’s context id, as returned by
 *              ctk_statusbar_get_context_id()
 * @text: the message to add to the statusbar
 * 
 * Pushes a new message onto a statusbar’s stack.
 *
 * Returns: a message id that can be used with 
 *          ctk_statusbar_remove().
 */
guint
ctk_statusbar_push (CtkStatusbar *statusbar,
		    guint	  context_id,
		    const gchar  *text)
{
  CtkStatusbarPrivate *priv;
  CtkStatusbarMsg *msg;

  g_return_val_if_fail (CTK_IS_STATUSBAR (statusbar), 0);
  g_return_val_if_fail (text != NULL, 0);

  priv = statusbar->priv;

  msg = ctk_statusbar_msg_create (statusbar, context_id, text);
  priv->messages = g_slist_prepend (priv->messages, msg);

  g_signal_emit (statusbar,
		 statusbar_signals[SIGNAL_TEXT_PUSHED],
		 0,
		 msg->context_id,
		 msg->text);

  return msg->message_id;
}

/**
 * ctk_statusbar_pop:
 * @statusbar: a #CtkStatusbar
 * @context_id: a context identifier
 * 
 * Removes the first message in the #CtkStatusbar’s stack
 * with the given context id. 
 *
 * Note that this may not change the displayed message, if 
 * the message at the top of the stack has a different 
 * context id.
 */
void
ctk_statusbar_pop (CtkStatusbar *statusbar,
		   guint	 context_id)
{
  CtkStatusbarPrivate *priv;
  CtkStatusbarMsg *msg;

  g_return_if_fail (CTK_IS_STATUSBAR (statusbar));

  priv = statusbar->priv;

  if (priv->messages)
    {
      GSList *list;

      for (list = priv->messages; list; list = list->next)
	{
	  msg = list->data;

	  if (msg->context_id == context_id)
	    {
	      priv->messages = g_slist_remove_link (priv->messages, list);
	      ctk_statusbar_msg_free (msg);
	      g_slist_free_1 (list);
	      break;
	    }
	}
    }

  msg = priv->messages ? priv->messages->data : NULL;

  g_signal_emit (statusbar,
		 statusbar_signals[SIGNAL_TEXT_POPPED],
		 0,
		 (guint) (msg ? msg->context_id : 0),
		 msg ? msg->text : NULL);
}

/**
 * ctk_statusbar_remove:
 * @statusbar: a #CtkStatusbar
 * @context_id: a context identifier
 * @message_id: a message identifier, as returned by ctk_statusbar_push()
 *
 * Forces the removal of a message from a statusbar’s stack. 
 * The exact @context_id and @message_id must be specified.
 */
void
ctk_statusbar_remove (CtkStatusbar *statusbar,
		      guint	   context_id,
		      guint        message_id)
{
  CtkStatusbarPrivate *priv;
  CtkStatusbarMsg *msg;

  g_return_if_fail (CTK_IS_STATUSBAR (statusbar));
  g_return_if_fail (message_id > 0);

  priv = statusbar->priv;

  msg = priv->messages ? priv->messages->data : NULL;
  if (msg)
    {
      GSList *list;

      /* care about signal emission if the topmost item is removed */
      if (msg->context_id == context_id &&
	  msg->message_id == message_id)
	{
	  ctk_statusbar_pop (statusbar, context_id);
	  return;
	}
      
      for (list = priv->messages; list; list = list->next)
	{
	  msg = list->data;
	  
	  if (msg->context_id == context_id &&
	      msg->message_id == message_id)
	    {
	      priv->messages = g_slist_remove_link (priv->messages, list);
	      ctk_statusbar_msg_free (msg);
	      g_slist_free_1 (list);
	      
	      break;
	    }
	}
    }
}

/**
 * ctk_statusbar_remove_all:
 * @statusbar: a #CtkStatusbar
 * @context_id: a context identifier
 *
 * Forces the removal of all messages from a statusbar's
 * stack with the exact @context_id.
 *
 * Since: 2.22
 */
void
ctk_statusbar_remove_all (CtkStatusbar *statusbar,
                          guint         context_id)
{
  CtkStatusbarPrivate *priv;
  CtkStatusbarMsg *msg;
  GSList *prev, *list;

  g_return_if_fail (CTK_IS_STATUSBAR (statusbar));

  priv = statusbar->priv;

  if (priv->messages == NULL)
    return;

  /* We special-case the topmost message at the bottom of this
   * function:
   * If we need to pop it, we have to update various state and we want
   * an up-to-date list of remaining messages in that case.
   */
  prev = priv->messages;
  list = prev->next;

  while (list != NULL)
    {
      msg = list->data;

      if (msg->context_id == context_id)
        {
          prev->next = list->next;

          ctk_statusbar_msg_free (msg);
          g_slist_free_1 (list);

          list = prev->next;
        }
      else
        {
          prev = list;
          list = prev->next;
        }
    }

  /* Treat topmost message here */
  msg = priv->messages->data;
  if (msg->context_id == context_id)
    {
      ctk_statusbar_pop (statusbar, context_id);
    }
}

/**
 * ctk_statusbar_get_message_area:
 * @statusbar: a #CtkStatusbar
 *
 * Retrieves the box containing the label widget.
 *
 * Returns: (type Ctk.Box) (transfer none): a #CtkBox
 *
 * Since: 2.20
 */
CtkWidget*
ctk_statusbar_get_message_area (CtkStatusbar *statusbar)
{
  CtkStatusbarPrivate *priv;

  g_return_val_if_fail (CTK_IS_STATUSBAR (statusbar), NULL);

  priv = statusbar->priv;

  return priv->message_area;
}

static void
ctk_statusbar_destroy (CtkWidget *widget)
{
  CtkStatusbar *statusbar = CTK_STATUSBAR (widget);
  CtkStatusbarPrivate *priv = statusbar->priv;

  g_slist_free_full (priv->messages, (GDestroyNotify) ctk_statusbar_msg_free);
  priv->messages = NULL;

  g_slist_free_full (priv->keys, g_free);
  priv->keys = NULL;

  CTK_WIDGET_CLASS (ctk_statusbar_parent_class)->destroy (widget);
}
