deprecated_h_sources = 			\
	deprecated/ctkactivatable.h	\
	deprecated/ctkalignment.h	\
	deprecated/ctkarrow.h		\
	deprecated/ctkcolorsel.h	\
	deprecated/ctkcolorseldialog.h	\
	deprecated/ctkfontsel.h		\
	deprecated/ctkgradient.h	\
	deprecated/ctkhandlebox.h	\
	deprecated/ctkhbbox.h		\
	deprecated/ctkhbox.h		\
	deprecated/ctkhpaned.h		\
	deprecated/ctkhscale.h		\
	deprecated/ctkhscrollbar.h	\
	deprecated/ctkhseparator.h	\
	deprecated/ctkhsv.h		\
	deprecated/ctkimagemenuitem.h	\
	deprecated/ctkmisc.h		\
	deprecated/ctknumerableicon.h	\
	deprecated/ctkradioaction.h	\
	deprecated/ctkrecentaction.h	\
	deprecated/ctkstatusicon.h	\
	deprecated/ctkstyleproperties.h	\
	deprecated/ctksymboliccolor.h	\
	deprecated/ctktable.h		\
	deprecated/ctktearoffmenuitem.h	\
	deprecated/ctkthemingengine.h	\
	deprecated/ctkuimanager.h	\
	deprecated/ctkvbbox.h		\
	deprecated/ctkvbox.h		\
	deprecated/ctkvscale.h		\
	deprecated/ctkvscrollbar.h	\
	deprecated/ctkvseparator.h	\
	deprecated/ctkvpaned.h

deprecated_private_h_sources =			\
	deprecated/ctkgradientprivate.h		\
	deprecated/ctkiconfactoryprivate.h	\
	deprecated/ctknumerableiconprivate.h	\
	deprecated/ctkstylepropertiesprivate.h	\
	deprecated/ctksymboliccolorprivate.h

deprecated_c_sources = 			\
	deprecated/ctkactivatable.c	\
	deprecated/ctkalignment.c	\
	deprecated/ctkarrow.c		\
	deprecated/ctkcolorsel.c	\
	deprecated/ctkcolorseldialog.c	\
	deprecated/ctkfontsel.c		\
	deprecated/ctkgradient.c	\
	deprecated/ctkhandlebox.c	\
	deprecated/ctkhbbox.c		\
	deprecated/ctkhbox.c		\
	deprecated/ctkhpaned.c		\
	deprecated/ctkhscale.c		\
	deprecated/ctkhscrollbar.c	\
	deprecated/ctkhseparator.c	\
	deprecated/ctkhsv.c		\
	deprecated/ctkimagemenuitem.c	\
	deprecated/ctkmisc.c		\
	deprecated/ctknumerableicon.c	\
	deprecated/ctkradioaction.c	\
	deprecated/ctkrecentaction.c	\
	deprecated/ctkstatusicon.c	\
	deprecated/ctkstyleproperties.c	\
	deprecated/ctksymboliccolor.c	\
	deprecated/ctktable.c		\
	deprecated/ctktearoffmenuitem.c	\
	deprecated/ctkthemingengine.c	\
	deprecated/ctkuimanager.c	\
	deprecated/ctkvbbox.c		\
	deprecated/ctkvbox.c		\
	deprecated/ctkvscale.c		\
	deprecated/ctkvscrollbar.c	\
	deprecated/ctkvseparator.c	\
	deprecated/ctkvpaned.c
